services:
  frontend:
    build: ./frontend
    container_name: next
    hostname: next
    ports:
      - "3010:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://fastapi:8000
      - NEXTAUTH_URL=http://localhost:3010
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3010"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - fastapi

  fastapi:
    build: ./backend
    container_name: fastapi
    environment:
      - STAGE=development
      - PYTHONUNBUFFERED=1
      - BENTOML_HOST=http://bentoml-service:3000/
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
      - bentoml-service

  bentoml-service:
    build:
      context: ./backend/bentoml
      dockerfile: Dockerfile
    ports:
      - "5010:3000"
    hostname: bentoml-service
    container_name: bentoml-service
    env_file:
      - ./backend/bentoml/.env
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5010/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - frontend
      - fastapi
      - bentoml-service
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
