services:
  frontend:
    build: ./frontend
    container_name: next
    hostname: next
    ports:
      - "3010:3000"
    # depends_on:
    #   fastapi:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  fastapi:
    build: ./backend
    container_name: fastapi
    environment:
      - STAGE=development
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  bentoml:
    # image: dynamic_regression_service:u7brafqdhwdnxeum
    build: 
      context: ./backend/bentoml
      dockerfile: Dockerfile
    container_name: bentoml
    environment:
      - BENTOML_ENV=development
    ports:
      - "5010:5000"
    # depends_on:
    #   fastapi:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5010/health"]
      interval: 30s
      timeout: 10s
      retries: 5
