services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      bentoml:
        condition: service_healthy
    healthcheck:
      test: ["curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 3

  bentoml:
    build: ./backend/bentoml
    ports:
      - "5010:5010"
    healthcheck:
      test: ["curl", "-f", "http://localhost:5010"]
      interval: 10s
      timeout: 5s
      retries: 3
