services:
  frontend:
    build: ./frontend
    container_name: next
    hostname: next
    ports:
      - "3010:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://fastapi:8000
      - NEXTAUTH_URL=http://localhost:3010
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3010"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - fastapi
    restart: unless-stopped

  fastapi:
    build: ./backend
    container_name: fastapi
    environment:
      - STAGE=development
      - PYTHONUNBUFFERED=1
      - BENTOML_HOST=http://bentoml-service:3000/
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
      - bentoml-service
    restart: unless-stopped

  bentoml-service:
    build:
      context: ./backend/bentoml
      dockerfile: Dockerfile
    ports:
      - "5010:3000"
    hostname: bentoml-service
    container_name: bentoml-service
    env_file:
      - ./backend/bentoml/.env
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5010/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    env_file: .env
    depends_on:
      - frontend
      - fastapi
      - bentoml-service
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/secure/:/etc/nginx/templates/
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/99-autoreload.sh:/docker-entrypoint.d/99-autoreload.sh
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mynetwork

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'" # Renew certificates every 12 hours

networks:
  mynetwork:
    driver: bridge

