services:
  frontend:
    build: ./frontend
    container_name: next
    hostname: next
    ports:
      - "3000:3000"
    # depends_on:
    #   fastapi:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  fastapi:
    build: ./backend
    container_name: fastapi
    environment:
      - STAGE=development
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  bentoml:
    build: ./bentoml
    container_name: bentoml
    environment:
      - BENTOML_ENV=development
    ports:
      - "5000:5000"
    # Optionally, you can depend on FastAPI if this service also needs it.
    depends_on:
      fastapi:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
