name: Sync Subtrees to Split Repos

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - "backend/**"

jobs:
  sync-subtrees:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          access-token: ${{ secrets.GG }}
          fetch-depth: 0 # Needed for full git history

      - name: Setup Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Push frontend subtree
        run: |
          git subtree push --prefix=frontend https://x-access-token:${{ secrets.GH_PAT }}@github.com/blackfenzer/meniscus-frontend-repo.git main

      - name: Push backend subtree
        run: |
          git subtree push --prefix=backend https://x-access-token:${{ secrets.GH_PAT }}@github.com/blackfenzer/meniscus-backend-repo.git main
